### PR TITLE
Port To Gtk 3, TelepathyGLib, and Other Fixes [WIP]

### PR DESCRIPTION
**Pull request by Creatune**
@quozl @walterbender Please help :)

### CODE REVIEW

**Comment by Creatune** [comment]
I am currently getting the following error:
https://asciinema.org/a/vuWsWITMPD09scBP7GvQOTUlp
I do not know how to solve this. Please help

**Comment by Creatune** [comment]
I am also planning to port this to Gst.get_structure() after successfully porting to Gtk 3

**Comment by quozl** [comment]
Oops, I think we may have given you bad instructions.  Issue https://github.com/sugarlabs/amazonas-activity/issues/2 sets the scene, and you should have checked for issues before starting.

Amazonas activity is a fork of [TurtleArt](https://github.com/sugarlabs/turtleart-activity) and is also in the [stale branch amazonas](https://github.com/sugarlabs/turtleart-activity/tree/amazonas).  A git history visualisation shows _amazonas_ branch to be connected to _master_ branch about seven years ago, just after the _v178_ tag.  The changes between _master_ back then and _amazonas_ is what made Amazonas out of TurtleArt.  Let's call that the _Delta_.  The _Delta_ is just four patches.

Porting to GTK 3 is best done by reverting the _Delta_, bringing the Port to GTK 3, GStreamer, and Port to Python 3 changes from TurtleArt, and then forward-porting the _Delta_.

You can see how **very difficult** this is by reviewing @Kiy4h's work on [another fork activity](https://github.com/sugarlabs/TortugadeMexico/pull/4).

You should budget a few weeks.  If you don't think you can do that, let us know so we can close the pull request.

**Comment by Creatune** [comment]
Sure, I will try my best to fix it. But probably after March as I have a college entrance test to give currently (SAT).

**Comment by quozl** [comment]
Okay, thanks, I don't know what SAT is, but if you do resume work on this please open a new pull request.

**Pull request closed without merging**
